import type { Metadata } from 'next';
import { Geist, Geist_Mono, UnifrakturCook } from 'next/font/google';
import Footer from './_layout/Footer';
import Header from './_layout/Header';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const tyrian = UnifrakturCook({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-tyrian',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tyrian.variable} antialiased relative min-h-screen bg-tyrian-hero text-white`}
      >
        <Header />
        <main className='container-full'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
