import type { Metadata } from 'next';
import Footer from './_layout/Footer';
import Header from './_layout/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='vi'>
      <body
        className={`antialiased relative min-h-screen bg-tyrian-hero text-white`}
      >
        <Header />
        <main className='main'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
